const translations = {
    RU: {
        menu: "Меню",
        home: "Главная",
        performances: "Репертуар",
        about: "О театре",
        backstage: "За кулисами",
        repertoire: "Афиша",
        contact: "Контакты",
        footerDescription: "Мы создаем незабываемые впечатления в мире балета. Подпишитесь на наши обновления и будьте в курсе всех новостей.",
        navigation: "Навигация",
        contactInfo: "Контактная информация",
        phone: "Телефон",
        socialMedia: "Мы в социальных сетях",
        companyName: "Abay Opera House",
        allRightsReserved: "Все права защищены",

        performers: "Исполнители",
    creativeTeam: "Креативная команда",
      
      // HomePage
      heroTitle: "Перед столетием",
      heroSubtitle: "91 театральный сезон",
      viewPerformances: "ПОСМОТРЕТЬ АФИШУ",
      classicPerformancesTitle: "КЛАССИЧЕСКИЕ ПОСТАНОВКИ В СОВРЕМЕННОМ МИРЕ",
      classicPerformancesDescription: "Наш балет — это незабываемое событие: окунитесь в мир классического искусства не только во время выступления, но и за его пределами. Встречайтесь с артистами и постановщиками, а также оставайтесь на связи с нами в режиме онлайн.",
      performancesTitle: "Афиша",
      performanceDate: "Дата",
      loading: "Загрузка...",
      aboutTheatreTitle: "О театре",
      aboutTheatreDescription: "Казахский национальный театр оперы и балета им. Абая — одно из знаковых культурных учреждений Алматы, основанное в 1933 году. Театр является центром оперного и балетного искусства Казахстана, объединяющим традиции и современные достижения.",
      readMoreAboutTheatre: "Подробнее о театре",
      backstagesTitle: "За кулисами",
      backstageDate: "Дата",
      

        // PerformanceDetailPage
    description: "Описание",
    history: "История",
    libretto: "Либретто",
    showMore: "Показать больше",
    showLess: "Показать меньше",
    dateAndTime: "Дата и время",
    composer: "Композитор",
    premiere: "Премьера в KAZNTOB",
    genre: "Жанр",
    duration: "Продолжительность",
    rolesAndPerformers: "Действующие лица и исполнители",
    buyTicket: "Купить билет",
    loading: "Загрузка...",


      aboutTheatreHistory: "О театре",
    aboutTheatreIntro: "Решением коллегии Народного Комиссариата просвещения Казахской АССР от 29 сентября 1933 года в Алма-Ате была создана музыкальная студия, состоявшая из пятидесяти актёров, двадцати музыкантов симфонического и двенадцати человек национального оркестра.",
    aboutTheatreFirstPerformance: "13 января 1934 года состоялось первое публичное исполнение музыкальной комедии «Айман-Шолпан», поставленной силами музыкальной студии по пьесе М.О.Ауэзова, ознаменовавшее, в соответствии с решением Наркомпроса, рождение первого «казахского музыкального театра оперы и балета».",
    aboutTheatreConstruction: "Строительство здания театра по проекту московского архитектора Н.А. Круглова началось в 1936 году и было завершено в 1941 году архитекторами Н.А. Простаковым и Т.К. Басеновым.",
    aboutTheatreOpening: "7 ноября 1941 года Театр открылся в собственном здании. В этом же году театр получил статус академического, а в 1945 году ему было присвоено имя Абая.",
    aboutTheatreRenovation: "С июня 1995 по 13 декабря 2000 года в театре была осуществлена генеральная реконструкция, сохранившая основной архитектурный стиль — ампир, сочетающийся с итальянским классицизмом и традиционными элементами национальной формы в архитектуре Казахстана.",
    aboutTheatreConclusion: "Современный КазНТОБ имени Абая — один из крупнейших театров Евразийского пространства, в творческом составе которого наряду с прославленными мастерами сцены оттачивают своё искусство и молодые таланты.",
    
    aboutMuseumTitle: "Театральный музей",
    aboutMuseumIntro: "Театральный музей Казахского национального театра оперы и балета имени Абая был открыт в марте 2016 года. Его создание — результат плодотворного сотрудничества руководства, сотрудников театра и меценатов.",
    aboutMuseumFirstExhibit: "Во-первых, это редкие архивные фотодокументы, связанные с деятельностью основателей театра, с жизнью и работой людей, которые верили, что искусство изменит мир.",
    aboutMuseumSecondExhibit: "Во-вторых, в музее вы найдете театральные костюмы, в которых когда-то выступали известные артисты оперы и балета КазНТОБ им. Абая.",
    aboutMuseumThirdExhibit: "В-третьих, важной частью музея является «зал эскизов и афиш», где вы увидите редкие театральные афиши и эскизы костюмов.",
    aboutMuseumConclusion: "Мы надеемся, что наш музей приоткроет для вас завесу театральной тайны, и вы увидите, как складывалась история театра.",
  
    roles: "Роли",
    creativeTeam: "Креативная команда",
    showMore: "Показать больше",
    showLess: "Показать меньше",
    loading: "Загрузка...",
    noDescription: "Нет описания"
    },
    EN: {
        menu: "Menu",
        home: "Home",
        performances: "Repertoire",
        repertoire: "Performances",
        about: "About Us",
        backstage: "Backstage",
        contact: "Contact",
        footerDescription: "We create unforgettable experiences in the world of ballet. Subscribe to our updates and stay informed of all news.",
        navigation: "Navigation",
        contactInfo: "Contact Information",
        phone: "Phone",
        socialMedia: "Follow us on social media",
        companyName: "Abay Opera House",
        allRightsReserved: "All rights reserved",
      
      // HomePage
      heroTitle: "Before the Centennial",
      heroSubtitle: "91st Theatrical Season",
      viewPerformances: "VIEW PERFORMANCES",
      classicPerformancesTitle: "CLASSIC PERFORMANCES IN THE MODERN WORLD",
      classicPerformancesDescription: "Our ballet is an unforgettable experience: immerse yourself in the world of classical art not only during the performance but also beyond it. Meet the artists and directors, and stay connected with us online.",
      performancesTitle: "Performances",
      performanceDate: "Date",
      loading: "Loading...",
      aboutTheatreTitle: "About the Theatre",
      aboutTheatreDescription: "The Kazakh National Opera and Ballet Theatre named after Abay is one of the landmark cultural institutions in Almaty, founded in 1933. The theatre is the center of opera and ballet art in Kazakhstan, combining traditions and modern achievements.",
      readMoreAboutTheatre: "Read more about the theatre",
      backstagesTitle: "Backstage",
      backstageDate: "Date",
      performers: "Performers",
    creativeTeam: "Creative Team",

      description: "Description",
      history: "History",
      libretto: "Libretto",
      showMore: "Show More",
      showLess: "Show Less",
      dateAndTime: "Date and Time",
      composer: "Composer",
      premiere: "Premiere in KAZNTOB",
      genre: "Genre",
      duration: "Duration",
      rolesAndPerformers: "Roles and Performers",
      buyTicket: "Buy Ticket",
      loading: "Loading...",

      aboutTheatreHistory: "About the Theatre",
      aboutTheatreIntro: "By decision of the People's Commissariat of Education of the Kazakh SSR on September 29, 1933, a music studio was created, consisting of fifty actors, twenty symphony musicians, and twelve members of a national orchestra.",
      aboutTheatreFirstPerformance: "On January 13, 1934, the first public performance of the musical comedy 'Aiman-Sholpan', directed by the music studio based on the play by M.O. Auezov, marked the birth of the first 'Kazakh Musical Opera and Ballet Theatre'.",
      aboutTheatreConstruction: "The construction of the theatre building, designed by Moscow architect N.A. Kruglov, began in 1936 and was completed in 1941 by architects N.A. Prostakov and T.K. Basenov.",
      aboutTheatreOpening: "On November 7, 1941, the theatre opened in its own building. In the same year, it received the status of an academic theatre, and in 1945 it was named after Abay.",
      aboutTheatreRenovation: "From June 1995 to December 13, 2000, a major renovation was carried out in the theatre, preserving the Empire style, combined with Italian classicism and traditional elements of Kazakh architecture.",
      aboutTheatreConclusion: "The modern Abay Opera House is one of the largest theatres in the Eurasian space, where young talents hone their skills alongside renowned stage masters.",
      
      aboutMuseumTitle: "Theatre Museum",
      aboutMuseumIntro: "The Theatre Museum of the Kazakh National Opera and Ballet Theatre named after Abay was opened in March 2016. Its creation is the result of fruitful cooperation between the theatre’s management, staff, and patrons.",
      aboutMuseumFirstExhibit: "Firstly, these are rare archival photo documents related to the founders of the theatre and the lives of people who believed that art could change the world.",
      aboutMuseumSecondExhibit: "Secondly, the museum contains stage costumes once worn by famous opera and ballet artists of the Abay Opera House.",
      aboutMuseumThirdExhibit: "Thirdly, an important part of the museum is the 'Sketches and Posters Hall,' where you can see rare theatrical posters and costume sketches.",
      aboutMuseumConclusion: "We hope that our museum will lift the veil of theatrical mystery for you and show you the history of the theatre.",
    
      roles: "Roles",
    creativeTeam: "Creative Team",
    showMore: "Show More",
    showLess: "Show Less",
    loading: "Loading...",
    noDescription: "No description"
    },
    KZ: {
        menu: "Мәзір",
        home: "Басты бет",
        performances: "Репертуар",
        about: "Театр туралы",
        repertoire: "Афиша",
        backstage: "Сахна сырты",
        contact: "Байланыс",
        footerDescription: "Біз балет әлеміндегі ұмытылмас әсерлерді жасаймыз. Жаңартуларымызға жазылыңыз және барлық жаңалықтардан хабардар болыңыз.",
        navigation: "Навигация",
        contactInfo: "Байланыс мәліметтері",
        phone: "Телефон",
        socialMedia: "Әлеуметтік желілерде бізді бақылаңыз",
        companyName: "Abay Opera House",
        allRightsReserved: "Барлық құқықтар қорғалған",
        performers: "Орындаушылар",
    creativeTeam: "Шығармашылық топ",
      
      // HomePage
      heroTitle: "Ғасыр алдындағы",
      heroSubtitle: "91-ші театр маусымы",
      viewPerformances: "АФИШАНЫ ҚАРАУ",
      classicPerformancesTitle: "ҚАЗІРГІ ӘЛЕМДЕГІ КЛАССИКАЛЫҚ ҚОЙЫЛЫМДАР",
      classicPerformancesDescription: "Біздің балет — бұл ұмытылмас оқиға: классикалық өнер әлеміне тек қойылым барысында ғана емес, одан тыс та еніңіз. Артистер мен режиссерлермен кездесіп, бізбен онлайн режимде байланыста болыңыз.",
      performancesTitle: "Афиша",
      performanceDate: "Күні",
      loading: "Жүктелуде...",
      aboutTheatreTitle: "Театр туралы",
      aboutTheatreDescription: "Абай атындағы Қазақ ұлттық опера және балет театры — 1933 жылы құрылған Алматыдағы маңызды мәдени мекемелердің бірі. Театр Қазақстандағы опера және балет өнерінің орталығы болып табылады, дәстүрлер мен заманауи жетістіктерді біріктіреді.",
      readMoreAboutTheatre: "Театр туралы толығырақ",
      backstagesTitle: "Сахна артында",
      backstageDate: "Күні",

      description: "Сипаттамасы",
      history: "Тарих",
      libretto: "Либретто",
      showMore: "Көбірек көрсету",
      showLess: "Аз көрсету",
      dateAndTime: "Күні және уақыты",
      composer: "Композитор",
      premiere: "Премьерасы KAZNTOB",
      genre: "Жанр",
      duration: "Ұзақтығы",
      rolesAndPerformers: "Қатысушылар мен орындаушылар",
      buyTicket: "Билет сатып алу",
      loading: "Жүктелуде...",


      aboutTheatreHistory: "Театр туралы",
    aboutTheatreIntro: "1933 жылғы 29 қыркүйекте Қазақ КСР Халық ағарту комиссариатының шешімімен Алматыда музыкалық студия құрылды, құрамында елу актер, жиырма симфониялық музыкант және ұлттық оркестрдің он екі мүшесі бар.",
    aboutTheatreFirstPerformance: "1934 жылғы 13 қаңтарда М.О. Әуезовтің пьесасы бойынша музыкалық студия қойған «Айман-Шолпан» музыкалық комедиясының алғашқы қойылымы өтті, бұл 'қазақ музыкалық опера және балет театрының' дүниеге келуін белгіледі.",
    aboutTheatreConstruction: "Театр ғимаратының құрылысы мәскеулік сәулетші Н.А. Кругловтың жобасы бойынша 1936 жылы басталып, 1941 жылы сәулетшілер Н.А. Простаков және Т.К. Басеновтің басшылығымен аяқталды.",
    aboutTheatreOpening: "1941 жылғы 7 қарашада театр өз ғимаратында ашылды. Сол жылы академиялық театр мәртебесіне ие болды, ал 1945 жылы Абай есімі берілді.",
    aboutTheatreRenovation: "1995 жылдың маусымынан 2000 жылдың 13 желтоқсанына дейін театрда қайта құру жұмыстары жүргізіліп, ампир стилі, итальяндық классицизм және қазақ ұлттық сәулетінің элементтері сақталды.",
    aboutTheatreConclusion: "Қазіргі Абай атындағы ҚазҰОБТ — Еуразия кеңістігіндегі ең ірі театрлардың бірі, мұнда танымал сахна шеберлері мен жас таланттар өз өнерін шыңдайды.",
    
    aboutMuseumTitle: "Театр мұражайы",
    aboutMuseumIntro: "Абай атындағы Қазақ ұлттық опера және балет театрының мұражайы 2016 жылғы наурызда ашылды. Мұражайдың ашылуы театр басшылығының, қызметкерлерінің және меценаттардың жемісті ынтымақтастығының нәтижесі болып табылады.",
    aboutMuseumFirstExhibit: "Біріншіден, бұл театр негізін қалаушылардың қызметіне және олардың өнер әлеміне деген сенімдеріне қатысты сирек кездесетін мұрағаттық фотосуреттер.",
    aboutMuseumSecondExhibit: "Екіншіден, мұражайда Абай атындағы ҚазҰОБТ-ның әйгілі опера және балет әртістері киген сахналық костюмдері қойылған.",
    aboutMuseumThirdExhibit: "Үшіншіден, мұражайдың маңызды бөлігі — «Эскиздер мен афишалар залы», онда сіз сирек кездесетін театр афишалары мен костюм эскиздерін көре аласыз.",
    aboutMuseumConclusion: "Мұражайымыз театр тарихын ашып көрсетеді деп үміттенеміз.",
  
    roles: "Рөлдер",
    creativeTeam: "Шығармашылық топ",
    showMore: "Көбірек көрсету",
    showLess: "Аз көрсету",
    loading: "Жүктелуде...",
    noDescription: "Сипаттама жоқ"
    },
  };
  
  export default translations;
  